export const CONVERT_CURRENCY_START = "CONVERT_CURRENCY_START";
export const CONVERT_CURRENCY_SUCCESS = "CONVERT_CURRENCY_SUCCESS";
export const CONVERT_CURRENCY_ERROR = "CONVERT_CURRENCY_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
