export const CONVERT_CURRENCY_START = "CONVERT_CURRENCY_START";
export const CONVERT_CURRENCY_SUCCESS = "CONVERT_CURRENCY_SUCCESS";
export const CONVERT_CURRENCY_ERROR = "CONVERT_CURRENCY_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export const GET_CATEGORY_NAME_START = "GET_CATEGORY_NAME_START";
export const GET_CATEGORY_NAME_SUCCESS = "GET_CATEGORY_NAME_SUCCESS";
export const GET_CATEGORY_NAME_FAILURE = "GET_CATEGORY_NAME_FAILURE";

export const GET_COLOR_START = "GET_COLOR_START";
export const GET_COLOR_SUCCESS = "GET_COLOR_SUCCESS";
export const GET_COLOR_FAILURE = "GET_COLOR_FAILURE";

export const GET_ATTRIBUTE_VALUE_START = "GET_ATTRIBUTE_VALUE_START";
export const GET_ATTRIBUTE_VALUE_SUCCESS = "GET_ATTRIBUTE_VALUE_SUCCESS";
export const GET_ATTRIBUTE_FAILURE = "GET_ATTRIBUTE_FAILURE";
